### PR TITLE
added option to enable/disable stricy ntlm

### PR DESCRIPTION
**Pull request by maa105**
That is if the server does not require ntlm the original response will be returned optionally

### CODE REVIEW

**Comment by AmitBaranes** [comment]
Any ETA on this? fixed my issue as well.

**Comment by maa105** [comment]
@AmitBaranes you can use an npm package I created [httpntlm-maa](https://www.npmjs.com/package/httpntlm-maa) until this pull request is merged.

**Comment by AmitBaranes** [comment]
@maa105  Thanks, Much appreciated !

**Comment by SamDecrock** [comment]
If the server does not require NTLM, you can simply use https://www.npmjs.com/package/httpreq

**Pull request closed without merging**
